### ISSUE TITLE
No mob spawning in loaded worlds

### ISSUE THREAD

**Issue by wordandahalf** [Paul19988/Advanced-Slime-World-Manager#130]
**Describe the issue**
No natural mob spawning occurs in worlds loaded by ASWM, regardless of gamerule settings or difficulty.
Using `/swm create` and manually updating the difficulty and gamerules results in a world in which mobs spawn.

**Spigot version**
1.18.2

**Plugin version**
2.8.0-SNAPSHOT (ae292c4)

**How to reproduce**

Configure plugin to load world with mob spawning enabled:
```yml
worlds:
    world-name:
        source: file
        spawn: 0, 64, 0
        difficulty: hard
        allowMonsters: true
        allowAnimals: false
        dragonBattle: false
        pvp: false
        environment: NORMAL
        worldType: CUSTOMIZED
        defaultBiome: minecraft:plains
        loadOnStartup: true
        readOnly: true
```
Witness no mobs spawning. Spawners work, but natural mob spawning does not.

**Crash reports (if available)**
N/A
