### ISSUE TITLE
Crashes when overriding default world

### ISSUE THREAD

**Issue by seb303** [Paul19988/Advanced-Slime-World-Manager#98]
Works with /swm load & goto commands, but crashes on start-up when a SWM world name is specified in server.properties.

Strangely, the server also creates folders for the SWM world (e.g. "lobby", "lobby_the_end" - nether is disabled in server.properties)

server.properties
`level-name=lobby`

worlds.yml
```
worlds:
    lobby:
        source: file
        spawn: 0.5, 72, 0.5
        difficulty: peaceful
        allowMonsters: false
        allowAnimals: false
        dragonBattle: false
        pvp: false
        environment: NORMAL
        worldType: default
        defaultBiome: minecraft:plains
        loadOnStartup: true
        readOnly: false
```

Running Paper version git-Paper-408 (MC: 1.17.1) (Implementing API version 1.17.1-R0.1-SNAPSHOT)

Plugin is slimeworldmanager-plugin-2.7.0-SNAPSHOT

[14:17:29 INFO]: Preparing level "lobby"
[14:17:29 INFO]: [STDOUT] [net.minecraft.server.MinecraftServer] Overriding default worlds
[14:17:29 ERROR]: Encountered an unexpected exception
java.lang.NoSuchFieldException: Y
        at java.lang.Class.getField(Class.java:2086) ~[?:?]
        at net.minecraft.server.MinecraftServer.loadWorld(MinecraftServer.java) ~[patched_1.17.1.jar:git-Paper-408]
        at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:317) ~[patched_1.17.1.jar:git-Paper-408]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1220) ~[patched_1.17.1.jar:git-Paper-408]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:319) ~[patched_1.17.1.jar:git-Paper-408]
        at java.lang.Thread.run(Thread.java:831) ~[?:?]
[14:17:29 ERROR]: This crash report has been saved to: ..... 
[crash-2022-01-29_14.17.29-server.txt](https://github.com/Paul19988/Advanced-Slime-World-Manager/files/7963895/crash-2022-01-29_14.17.29-server.txt)
